#' Read log file generated by \code{ForceLogger}
#'
#' Read log file generated by \code{ForceLogger} and return structured log as \code{data.frame}.
#'
#' @param file A path of log file
#'
#' @export
readLog <- function(file) {
  logParsed <-
    readLines(file) %>%
    makeJsonListFromLog() %>%
    jsonlite::fromJSON(txt = .)

  logParsed$timestamp <- getDateTimeObjFromParsedLog(logParsed)

  return(logParsed)
}

makeJsonListFromLog <- function(logTxt) {
  sprintf("[%s]", paste0(logTxt, collapse = ","))
}

getDateTimeObjFromParsedLog <- function(logParsed) {
  dateTimeUtc <- parsedate::parse_iso_8601(logParsed$timestamp)
  dateTimeSysTz <-
    baseEncored::convertTimezone(dateTimeUtc, Sys.timezone())
  return(dateTimeSysTz)
}
